package ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import it.unimol.file.FileOutputRecord;
import it.unimol.gestori.GestoreInterfaccia;
import it.unimol.record.ListaRecord;
import it.unimol.record.Record;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 * classe utilizzata per far visualizzare al giocatore
 * la schermata GameOver in caso di sconfitta
 *
 * @author Francesco Chiacchiari
 */
public class GameOver {
    private JPanel panel1;
    private JButton bottoneEsci;
    private JButton bottoneRigioca;
    private JTextField campoNome;
    private JLabel scoreLabel;
    private FileOutputRecord fileOutputRecord = FileOutputRecord.getInstance();

    public GameOver(int punteggio, GestoreInterfaccia gestoreInterfaccia) {
        scoreLabel.setText(String.valueOf(punteggio));

        bottoneRigioca.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                gestoreInterfaccia.status = 1;
                gestoreInterfaccia.sceltaInterfaccia();
            }
        });
        bottoneEsci.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!campoNome.getText().isEmpty()) {
                    Record nuovoRecord = new Record();
                    nuovoRecord.setNomeGiocatore(campoNome.getText());
                    nuovoRecord.setPunteggioPartita(punteggio);
                    ListaRecord listaRecord = ListaRecord.getInstance();
                    listaRecord.aggiungiRecord(nuovoRecord);
                    fileOutputRecord.ScritturaSuFile(listaRecord.listaRecord);
                    System.out.println(nuovoRecord.getNomeGiocatore() + " " + nuovoRecord.getPunteggioPartita());
                }
                System.exit(0);
            }
        });
    }

    public JPanel getPanel1() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-14013137));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        bottoneEsci = new JButton();
        bottoneEsci.setBackground(new Color(-14013137));
        bottoneEsci.setEnabled(true);
        Font bottoneEsciFont = this.$$$getFont$$$("OCR A Extended", -1, -1, bottoneEsci.getFont());
        if (bottoneEsciFont != null) bottoneEsci.setFont(bottoneEsciFont);
        bottoneEsci.setForeground(new Color(-12544960));
        bottoneEsci.setHideActionText(true);
        bottoneEsci.setText("ESCI");
        panel2.add(bottoneEsci, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bottoneRigioca = new JButton();
        bottoneRigioca.setBackground(new Color(-14013137));
        Font bottoneRigiocaFont = this.$$$getFont$$$("OCR A Extended", -1, -1, bottoneRigioca.getFont());
        if (bottoneRigiocaFont != null) bottoneRigioca.setFont(bottoneRigiocaFont);
        bottoneRigioca.setForeground(new Color(-12544960));
        bottoneRigioca.setText("RIGIOCA");
        panel2.add(bottoneRigioca, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("OCR A Extended", Font.BOLD, 36, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setForeground(new Color(-4511988));
        label1.setText("GAME OVER");
        panel2.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        campoNome = new JTextField();
        campoNome.setBackground(new Color(-14013137));
        campoNome.setForeground(new Color(-12544960));
        campoNome.setText("");
        campoNome.setToolTipText("");
        panel2.add(campoNome, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        scoreLabel = new JLabel();
        Font scoreLabelFont = this.$$$getFont$$$("OCR A Extended", Font.BOLD, 20, scoreLabel.getFont());
        if (scoreLabelFont != null) scoreLabel.setFont(scoreLabelFont);
        scoreLabel.setForeground(new Color(-4511988));
        scoreLabel.setText("Label");
        panel2.add(scoreLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("OCR A Extended", Font.BOLD, 20, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-12544960));
        label2.setText("SCORE:");
        panel2.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
